language: dart
sudo: required
dart:
  - 1.24.3
  - stable
addons:
  chrome: stable
script:
  - pub get
  - pub run dart_dev analyze
  - pub run dart_dev format --check
  - pub run dart_dev test -p vm -p chrome
  - pub run dart_dev test --release -p chrome
